spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        trace: true
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://127.0.0.1:3306/flowable?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoint:
    flowable:
      enabled: true
