server:
  port:
    8080

spring:
  datasource:
    username: postgres
    password: 17358870357yi
    url: jdbc:postgresql://172.17.0.2:5432/postgres
    platform: postgres
    initialization-mode: always
    schema:
      - classpath:sql/schema.sql
    data:
      - classpath:sql/data.sql
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
  data:
    rest:
      base-path: /info
      default-page-size: 4
