// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserCustomer.proto

package org.xhliu.demo.rdo;

/**
 * Protobuf type {@code CustomerBasic}
 */
public final class CustomerBasic extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CustomerBasic)
    CustomerBasicOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CustomerBasic.newBuilder() to construct.
  private CustomerBasic(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CustomerBasic() {
    customerName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CustomerBasic();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CustomerBasic(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            customerId_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000002;
            customerName_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.xhliu.demo.rdo.CustomerInfo.internal_static_CustomerBasic_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.xhliu.demo.rdo.CustomerInfo.internal_static_CustomerBasic_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.xhliu.demo.rdo.CustomerBasic.class, org.xhliu.demo.rdo.CustomerBasic.Builder.class);
  }

  private int bitField0_;
  public static final int CUSTOMERID_FIELD_NUMBER = 1;
  private long customerId_;
  /**
   * <code>optional int64 customerId = 1;</code>
   * @return Whether the customerId field is set.
   */
  @java.lang.Override
  public boolean hasCustomerId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int64 customerId = 1;</code>
   * @return The customerId.
   */
  @java.lang.Override
  public long getCustomerId() {
    return customerId_;
  }

  public static final int CUSTOMERNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object customerName_;
  /**
   * <code>optional string customerName = 2;</code>
   * @return Whether the customerName field is set.
   */
  @java.lang.Override
  public boolean hasCustomerName() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string customerName = 2;</code>
   * @return The customerName.
   */
  @java.lang.Override
  public java.lang.String getCustomerName() {
    java.lang.Object ref = customerName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      customerName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string customerName = 2;</code>
   * @return The bytes for customerName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCustomerNameBytes() {
    java.lang.Object ref = customerName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      customerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt64(1, customerId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, customerName_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, customerId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, customerName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.xhliu.demo.rdo.CustomerBasic)) {
      return super.equals(obj);
    }
    org.xhliu.demo.rdo.CustomerBasic other = (org.xhliu.demo.rdo.CustomerBasic) obj;

    if (hasCustomerId() != other.hasCustomerId()) return false;
    if (hasCustomerId()) {
      if (getCustomerId()
          != other.getCustomerId()) return false;
    }
    if (hasCustomerName() != other.hasCustomerName()) return false;
    if (hasCustomerName()) {
      if (!getCustomerName()
          .equals(other.getCustomerName())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCustomerId()) {
      hash = (37 * hash) + CUSTOMERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCustomerId());
    }
    if (hasCustomerName()) {
      hash = (37 * hash) + CUSTOMERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getCustomerName().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.xhliu.demo.rdo.CustomerBasic parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.xhliu.demo.rdo.CustomerBasic parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.xhliu.demo.rdo.CustomerBasic parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.xhliu.demo.rdo.CustomerBasic parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.xhliu.demo.rdo.CustomerBasic parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.xhliu.demo.rdo.CustomerBasic parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.xhliu.demo.rdo.CustomerBasic parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.xhliu.demo.rdo.CustomerBasic parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.xhliu.demo.rdo.CustomerBasic parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.xhliu.demo.rdo.CustomerBasic parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.xhliu.demo.rdo.CustomerBasic parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.xhliu.demo.rdo.CustomerBasic parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.xhliu.demo.rdo.CustomerBasic prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CustomerBasic}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CustomerBasic)
      org.xhliu.demo.rdo.CustomerBasicOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.xhliu.demo.rdo.CustomerInfo.internal_static_CustomerBasic_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.xhliu.demo.rdo.CustomerInfo.internal_static_CustomerBasic_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.xhliu.demo.rdo.CustomerBasic.class, org.xhliu.demo.rdo.CustomerBasic.Builder.class);
    }

    // Construct using org.xhliu.demo.rdo.CustomerBasic.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      customerId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      customerName_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.xhliu.demo.rdo.CustomerInfo.internal_static_CustomerBasic_descriptor;
    }

    @java.lang.Override
    public org.xhliu.demo.rdo.CustomerBasic getDefaultInstanceForType() {
      return org.xhliu.demo.rdo.CustomerBasic.getDefaultInstance();
    }

    @java.lang.Override
    public org.xhliu.demo.rdo.CustomerBasic build() {
      org.xhliu.demo.rdo.CustomerBasic result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.xhliu.demo.rdo.CustomerBasic buildPartial() {
      org.xhliu.demo.rdo.CustomerBasic result = new org.xhliu.demo.rdo.CustomerBasic(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.customerId_ = customerId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.customerName_ = customerName_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.xhliu.demo.rdo.CustomerBasic) {
        return mergeFrom((org.xhliu.demo.rdo.CustomerBasic)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.xhliu.demo.rdo.CustomerBasic other) {
      if (other == org.xhliu.demo.rdo.CustomerBasic.getDefaultInstance()) return this;
      if (other.hasCustomerId()) {
        setCustomerId(other.getCustomerId());
      }
      if (other.hasCustomerName()) {
        bitField0_ |= 0x00000002;
        customerName_ = other.customerName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.xhliu.demo.rdo.CustomerBasic parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.xhliu.demo.rdo.CustomerBasic) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long customerId_ ;
    /**
     * <code>optional int64 customerId = 1;</code>
     * @return Whether the customerId field is set.
     */
    @java.lang.Override
    public boolean hasCustomerId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int64 customerId = 1;</code>
     * @return The customerId.
     */
    @java.lang.Override
    public long getCustomerId() {
      return customerId_;
    }
    /**
     * <code>optional int64 customerId = 1;</code>
     * @param value The customerId to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerId(long value) {
      bitField0_ |= 0x00000001;
      customerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 customerId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCustomerId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      customerId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object customerName_ = "";
    /**
     * <code>optional string customerName = 2;</code>
     * @return Whether the customerName field is set.
     */
    public boolean hasCustomerName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string customerName = 2;</code>
     * @return The customerName.
     */
    public java.lang.String getCustomerName() {
      java.lang.Object ref = customerName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        customerName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string customerName = 2;</code>
     * @return The bytes for customerName.
     */
    public com.google.protobuf.ByteString
        getCustomerNameBytes() {
      java.lang.Object ref = customerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string customerName = 2;</code>
     * @param value The customerName to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      customerName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string customerName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCustomerName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      customerName_ = getDefaultInstance().getCustomerName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string customerName = 2;</code>
     * @param value The bytes for customerName to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      customerName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CustomerBasic)
  }

  // @@protoc_insertion_point(class_scope:CustomerBasic)
  private static final org.xhliu.demo.rdo.CustomerBasic DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.xhliu.demo.rdo.CustomerBasic();
  }

  public static org.xhliu.demo.rdo.CustomerBasic getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CustomerBasic>
      PARSER = new com.google.protobuf.AbstractParser<CustomerBasic>() {
    @java.lang.Override
    public CustomerBasic parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CustomerBasic(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CustomerBasic> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CustomerBasic> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.xhliu.demo.rdo.CustomerBasic getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

