// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserCustomer.proto

package org.xhliu.demo.rdo;

public interface CustomerBasicOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CustomerBasic)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 customerId = 1;</code>
   * @return Whether the customerId field is set.
   */
  boolean hasCustomerId();
  /**
   * <code>optional int64 customerId = 1;</code>
   * @return The customerId.
   */
  long getCustomerId();

  /**
   * <code>optional string customerName = 2;</code>
   * @return Whether the customerName field is set.
   */
  boolean hasCustomerName();
  /**
   * <code>optional string customerName = 2;</code>
   * @return The customerName.
   */
  java.lang.String getCustomerName();
  /**
   * <code>optional string customerName = 2;</code>
   * @return The bytes for customerName.
   */
  com.google.protobuf.ByteString
      getCustomerNameBytes();
}
