server:
  port: 8080

spring:
  datasource:
    username: postgres
    password: 17358870357yi
    url: jdbc:postgresql://172.17.0.2:5432/postgres
    initialization-mode: never
    schema:
      -
        classpath:sql/schema.sql
    data:
      -
        classpath:sql/data.sql
  jpa:
    hibernate:
      ddl-auto: none